package com.miproyecto.proyecto.enums;

public enum IntentType {
    DESCONOCIDO,
    INVALIDA,
    DESCRIPCION_PLATAFORMA,
    DESCRIPCION_ASISTENTE,
    BUSQUEDA_EMPLEO,
    VACANTES,
    POSTULACION,
    REQUISITOS_POSTULACION,
    ESTADO_POSTULACION,
    PERFIL_USUARIO,
    TIPOS_EMPLEO,
    HERRAMIENTAS,
    SIN_PREGUNTA

}
